/**
 * This class is generated by jOOQ
 */
package me.illian.euromillions.jooq.tables.records;

import me.illian.euromillions.jooq.tables.Euromillions;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EuromillionsRecord extends org.jooq.impl.UpdatableRecordImpl<EuromillionsRecord> implements org.jooq.Record10<String, java.sql.Date, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

	private static final long serialVersionUID = -1423297536;

	/**
	 * Setter for <code>public.euromillions.year_draw_number</code>.
	 */
	public void setYearDrawNumber(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.euromillions.year_draw_number</code>.
	 */
	public String getYearDrawNumber() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.euromillions.draw_date</code>.
	 */
	public void setDrawDate(java.sql.Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.euromillions.draw_date</code>.
	 */
	public java.sql.Date getDrawDate() {
		return (java.sql.Date) getValue(1);
	}

	/**
	 * Setter for <code>public.euromillions.number_in_cycle</code>.
	 */
	public void setNumberInCycle(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.euromillions.number_in_cycle</code>.
	 */
	public Integer getNumberInCycle() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.euromillions.ball_1</code>.
	 */
	public void setBall_1(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.euromillions.ball_1</code>.
	 */
	public Integer getBall_1() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.euromillions.ball_2</code>.
	 */
	public void setBall_2(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.euromillions.ball_2</code>.
	 */
	public Integer getBall_2() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.euromillions.ball_3</code>.
	 */
	public void setBall_3(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.euromillions.ball_3</code>.
	 */
	public Integer getBall_3() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.euromillions.ball_4</code>.
	 */
	public void setBall_4(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.euromillions.ball_4</code>.
	 */
	public Integer getBall_4() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>public.euromillions.ball_5</code>.
	 */
	public void setBall_5(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.euromillions.ball_5</code>.
	 */
	public Integer getBall_5() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>public.euromillions.star_1</code>.
	 */
	public void setStar_1(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.euromillions.star_1</code>.
	 */
	public Integer getStar_1() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>public.euromillions.star_2</code>.
	 */
	public void setStar_2(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.euromillions.star_2</code>.
	 */
	public Integer getStar_2() {
		return (Integer) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<String, java.sql.Date, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<String, java.sql.Date, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field1() {
		return Euromillions.EUROMILLIONS.YEAR_DRAW_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field2() {
		return Euromillions.EUROMILLIONS.DRAW_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field3() {
		return Euromillions.EUROMILLIONS.NUMBER_IN_CYCLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field4() {
		return Euromillions.EUROMILLIONS.BALL_1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field5() {
		return Euromillions.EUROMILLIONS.BALL_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field6() {
		return Euromillions.EUROMILLIONS.BALL_3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field7() {
		return Euromillions.EUROMILLIONS.BALL_4;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field8() {
		return Euromillions.EUROMILLIONS.BALL_5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field9() {
		return Euromillions.EUROMILLIONS.STAR_1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field10() {
		return Euromillions.EUROMILLIONS.STAR_2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getYearDrawNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value2() {
		return getDrawDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getNumberInCycle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getBall_1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getBall_2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getBall_3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getBall_4();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getBall_5();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getStar_1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getStar_2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EuromillionsRecord value1(String value) {
		setYearDrawNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EuromillionsRecord value2(java.sql.Date value) {
		setDrawDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EuromillionsRecord value3(Integer value) {
		setNumberInCycle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EuromillionsRecord value4(Integer value) {
		setBall_1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EuromillionsRecord value5(Integer value) {
		setBall_2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EuromillionsRecord value6(Integer value) {
		setBall_3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EuromillionsRecord value7(Integer value) {
		setBall_4(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EuromillionsRecord value8(Integer value) {
		setBall_5(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EuromillionsRecord value9(Integer value) {
		setStar_1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EuromillionsRecord value10(Integer value) {
		setStar_2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EuromillionsRecord values(String value1, java.sql.Date value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EuromillionsRecord
	 */
	public EuromillionsRecord() {
		super(Euromillions.EUROMILLIONS);
	}

	/**
	 * Create a detached, initialised EuromillionsRecord
	 */
	public EuromillionsRecord(String yearDrawNumber, java.sql.Date drawDate, Integer numberInCycle, Integer ball_1, Integer ball_2, Integer ball_3, Integer ball_4, Integer ball_5, Integer star_1, Integer star_2) {
		super(Euromillions.EUROMILLIONS);

		setValue(0, yearDrawNumber);
		setValue(1, drawDate);
		setValue(2, numberInCycle);
		setValue(3, ball_1);
		setValue(4, ball_2);
		setValue(5, ball_3);
		setValue(6, ball_4);
		setValue(7, ball_5);
		setValue(8, star_1);
		setValue(9, star_2);
	}
}
