/**
 * This class is generated by jOOQ
 */
package me.illian.euromillions.jooq;

/**
 * A class modelling foreign key relationships between tables of the <code>public</code>
 * schema
 */
@javax.annotation.Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.5.4"
        },
        comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final org.jooq.UniqueKey<me.illian.euromillions.jooq.tables.records.EuromillionsRecord> FIRSTKEY = UniqueKeys0.FIRSTKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
        public static final org.jooq.UniqueKey<me.illian.euromillions.jooq.tables.records.EuromillionsRecord> FIRSTKEY = createUniqueKey(me.illian.euromillions.jooq.tables.Euromillions.EUROMILLIONS, me.illian.euromillions.jooq.tables.Euromillions.EUROMILLIONS.YEAR_DRAW_NUMBER);
    }
}
