/**
 * This class is generated by jOOQ
 */
package me.illian.euromillions.jooq;

/**
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.5.4"
        },
        comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table public.euromillions
     */
    public static final me.illian.euromillions.jooq.tables.Euromillions EUROMILLIONS = me.illian.euromillions.jooq.tables.Euromillions.EUROMILLIONS;
}
