/**
 * This class is generated by jOOQ
 */
package me.illian.euromillions.jooq.tables;

import me.illian.euromillions.jooq.tables.records.EuromillionsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.5.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Euromillions extends org.jooq.impl.TableImpl<EuromillionsRecord> {

    private static final long serialVersionUID = -417406764;

    /**
     * The reference instance of <code>public.euromillions</code>
     */
    public static final Euromillions EUROMILLIONS = new Euromillions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EuromillionsRecord> getRecordType() {
        return EuromillionsRecord.class;
    }

    /**
     * The column <code>public.euromillions.year_draw_number</code>.
     */
    public final org.jooq.TableField<EuromillionsRecord, String> YEAR_DRAW_NUMBER = createField("year_draw_number", org.jooq.impl.SQLDataType.CHAR.length(7).nullable(false), this, "");

    /**
     * The column <code>public.euromillions.draw_date</code>.
     */
    public final org.jooq.TableField<EuromillionsRecord, java.sql.Date> DRAW_DATE = createField("draw_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>public.euromillions.number_in_cycle</code>.
     */
    public final org.jooq.TableField<EuromillionsRecord, Integer> NUMBER_IN_CYCLE = createField("number_in_cycle", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.euromillions.ball_1</code>.
     */
    public final org.jooq.TableField<EuromillionsRecord, Integer> BALL_1 = createField("ball_1", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.euromillions.ball_2</code>.
     */
    public final org.jooq.TableField<EuromillionsRecord, Integer> BALL_2 = createField("ball_2", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.euromillions.ball_3</code>.
     */
    public final org.jooq.TableField<EuromillionsRecord, Integer> BALL_3 = createField("ball_3", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.euromillions.ball_4</code>.
     */
    public final org.jooq.TableField<EuromillionsRecord, Integer> BALL_4 = createField("ball_4", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.euromillions.ball_5</code>.
     */
    public final org.jooq.TableField<EuromillionsRecord, Integer> BALL_5 = createField("ball_5", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.euromillions.star_1</code>.
     */
    public final org.jooq.TableField<EuromillionsRecord, Integer> STAR_1 = createField("star_1", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.euromillions.star_2</code>.
     */
    public final org.jooq.TableField<EuromillionsRecord, Integer> STAR_2 = createField("star_2", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.euromillions</code> table reference
     */
    public Euromillions() {
        this("euromillions", null);
    }

    /**
     * Create an aliased <code>public.euromillions</code> table reference
     */
    public Euromillions(String alias) {
        this(alias, Euromillions.EUROMILLIONS);
    }

    private Euromillions(String alias, org.jooq.Table<EuromillionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Euromillions(String alias, org.jooq.Table<EuromillionsRecord> aliased, org.jooq.Field<?>[] parameters) {
        super(alias, me.illian.euromillions.jooq.Public.PUBLIC, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.UniqueKey<EuromillionsRecord> getPrimaryKey() {
        return me.illian.euromillions.jooq.Keys.FIRSTKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.util.List<org.jooq.UniqueKey<EuromillionsRecord>> getKeys() {
        return java.util.Arrays.<org.jooq.UniqueKey<EuromillionsRecord>>asList(me.illian.euromillions.jooq.Keys.FIRSTKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Euromillions as(String alias) {
        return new Euromillions(alias, this);
    }

    /**
     * Rename this table
     */
    public Euromillions rename(String name) {
        return new Euromillions(name, null);
    }
}
